### ISSUE TITLE
Question: Available for Python 3

### ISSUE THREAD

**Issue by mdvmh** [collective/plone.formwidget.masterselect#17]
We are happy to use plone.formwidget.masterselect in our Plone projects, which we are migrating to Python 3. Are there plans to make plone.formwidget.masterselect available for Python 3 ?

**Comment by wkbkhard** [comment]
I need this AddOn for one of our websites, so I'll try and Update a Python3-Branch for it (at the moment it is still new and not tested)!

**Comment by wkbkhard** [comment]
I guess my branch is working now (as far as I have tested it) - so feel free to use/test it. Pull request is made

**Comment by mdvmh** [comment]
Thank you for your work and your note!

**Comment by laulaz** [comment]
This one should be fixed when #19 is merged 👍
