### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wesleybl** [collective/plone.formwidget.masterselect#35]
Can someone please create a new release? I don't have permission on pypi.

@tisto @jensens @tdesvenain @vincentfretin 

Thanks!

**Comment by vincentfretin** [comment]
@sgeulette or @gbastien should be able to create a new release too. I know they were using this add-on in some projects. I'll leave it to them to review the latest changes and make a new release. I don't maintain any Plone projects since several years now, so I don't want to spend time on this.

**Comment by wesleybl** [comment]
@mauritsvanrees  gave me permission on pypi and I generated a new version:

https://pypi.org/project/plone.formwidget.masterselect/2.0.1

Thanks!
