### ISSUE TITLE
JSON query url is wrong in subpath urls

### ISSUE THREAD

**Issue by erral** [collective/plone.formwidget.masterselect#37]
See https://github.com/plone/plone.app.content/issues/103 the same happens here because of the use of `self.request.physicalPathFromURL(self.request.getURL())` at https://github.com/collective/plone.formwidget.masterselect/blob/master/src/plone/formwidget/masterselect/widget.py#L72-L74

**Comment by mauritsvanrees** [comment]
I have released your fixes in 1.8 and 3.0.0.  Thanks.
